### ISSUE TITLE
undefined symbol: XGDMatrixCreateFromFile

### ISSUE THREAD

**Issue by delanoe** [sighingnow/xgboost-haskell#1]
Hello,
thanks for this library.

Running the example (and same for the app for XGDMAtrixCreateFromMat), I got
undefined symbol: XGDMatrixCreateFromFile

I wonder if it is because of my version of xgboost or the current state of the library.
Do you have any idea ?
Thanks in advance.

**Comment by sighingnow** [comment]
Did the error occur when you build the app, or happened when running the app?

Could you provide the version information of xgboost library you use ?

**Comment by delanoe** [comment]
Hello,
I can compile without any error (with lts-9.9 for stack see my branch: https://github.com/delanoe/xgboost-haskell.git ), but the error occurs when running the agaricus example:

stack runghc examples/agaricus.hs 
xgboost example: agaricus
/home/user/.stack/programs/x86_64-linux/ghc-nopie-8.0.2/lib/ghc-8.0.2/bin/ghc: symbol lookup error: /home/user/local/logiciels/haskell/machineLearning/xgboost-haskell/.stack-work/install/x86_64-linux-nopie/lts-9.9/8.0.2/lib/x86_64-linux-ghc-8.0.2/libHSxgboost-haskell-0.1.0.0-1a2AWSA3FgAAr0JXN1wwp3-ghc8.0.2.so: undefined symbol: XGDMatrixCreateFromFile

xgboost has been built with last version on master (commit 5dca6745e11124df9792b81358fa55056fc74bb9)
on Debian Stable (Stretch) uptodate. 

inside the xgboost-haskell repo:
ln -s pathTo/libxgboost.so

Which version of xgboost do you use (which commit exactly) ? Or do you see any other step to test?

**Comment by sighingnow** [comment]
I think the issue is due to `runghc` doesn't link to the xgboost library correctly. I don't know how to pass extra libraries to `runghc`.

Could you try execute the example using the following commands ?

~~~
stack build && stack exec xgb-agaricus
~~~

**Comment by sighingnow** [comment]
Or, you could run the example using the following command:

~~~
stack exec -- runghc -lxgboost -fobject-code -fforce-recomp examples/agaricus.hs
~~~

You also need merge the changeset e772225c22 to your local repo, this fixed the missing `\0` at the end of string when pass strings to C functions.

**Comment by delanoe** [comment]
stack build && stack exec xgb-agaricus
works only after:
sudo ln -s $SOMEPATH/xgboost/lib/libxgboost.so /usr/lib

And your line:
stack exec -- runghc -lxgboost -fobject-code -fforce-recomp examples/agaricus.hs

Works indeed 

Great job!
Many thanks!

**Comment by sighingnow** [comment]
The soft link of `libxgboost.so` is not necessary.

You can add the directory which contains the `libxgboost.so` to the `LD_LIBRARY_PATH` environment variable.
